### PR TITLE
Fix lint issues and unit-tests

### PR DESCRIPTION
**Pull request by gaby**
* Fixes lint-issues introduced in #13 
* Fixes unit-test by adding `scheme` param to `setUp`

Confirmed test are passing here: https://github.com/gaby/rabbitmq-api-admin/actions/runs/2889366071

### CODE REVIEW

**Comment by gaby** [comment]
@PetrS12 Seems like my previous PR broke the unit-test and lint test. This PR fixes all those issues. 

Would it be possible to get a new release once this is merge?

Thank you for this awesome library!

**Comment by gaby** [comment]
@PetrS12 Also if you need help maintaining this library, let me know. :-)

**Comment by gaby** [comment]
@densypko Can you take a look at my changes? Thanks!

**Comment by densypko** [comment]
@gaby Looks nice.

**Comment by gaby** [comment]
> @gaby Looks nice.

Thanks! 👍🏻

**Comment by gaby** [comment]
* Bump Pika to 1.3.0
* Bump Coverage to 6.4.4
* Bump Flake8 to 5.0.4
* Bump github-actions to v3

This PR includes the changes from #15 #16 #17 #18

**Comment by gaby** [comment]
@PetrS12 Friendly bump :-)

**Review by PetrS12 — APPROVED** [review]

**Comment by PetrS12** [comment]
@gaby https://pypi.org/project/rabbitmq-api-admin/0.3.0/

**Comment by gaby** [comment]
@PetrS12 Thank you!

**Pull request merged**
